[_]
schema-version = "0.2"

[[io.buildpacks.build.env]]
name = "BUNDLE_WITHOUT"
value = ""

[[io.buildpacks.group]]
url = "https://github.com/reenhanced/buildpack-chrome-with-chromedriver/archive/refs/tags/1.0.2.tar.gz"
